jobs:
  - job: Build_Ubuntu1604
    pool:
      vmImage: ubuntu-16.04
    steps:
    # (PowerShell Core included in this Ubuntu image)

    - script: |
        docker run --rm -d -p 443:443/tcp nimmis/vcsim
      displayName: 'Run vCenter Simulator container'
    
    - powershell: |
        $null = Install-Module Pester, VMware.PowerCLI -Scope CurrentUser -AllowClobber -SkipPublisherCheck -Force
        Get-Module Pester, VMware.VimAutomation.Core -ListAvailable | Select-Object Version, Name | Format-Table -Autosize
      displayName: 'Install PowerShell Modules'
    
    - powershell: |
        $TestResults = Invoke-Pester -OutputFormat NUnitXml -OutputFile ".\TestResults.xml" -PassThru
        If ($TestResults.FailedCount -ne 0) {
            Write-Error "$($TestResults.FailedCount) test(s) failed"
        }
      displayName: 'Run Pester tests'
    
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testRunner:          'NUnit'
        testResultsFiles:    '**/TestResults.xml'
        testRunTitle:        'Ubuntu1604'
      displayName: 'Publish Test Results'
