jobs:
  - job: Build_Ubuntu1604
    pool:
      vmImage: ubuntu-16.04
    steps:
    # (PowerShell Core included in this Ubuntu image)

    # Install and run vcsim Docker container
    - script: |
        docker run --rm -d -p 443:443/tcp nimmis/vcsim
      displayName: 'Run vCenter Simulator container'
    
    # Run Pester tests
    - script: |
        pwsh -c '.\build.ps1'
      displayName: 'Build and Test'
    
    # Analyze test results
    - task: PublishTestResults@2
      inputs:
        testRunner:          'NUnit'
        testResultsFiles:    '**/TestResults.xml'
        testRunTitle:        'Ubuntu1604'
      displayName: 'Publish Test Results'
