jobs:
  - job: Build_Ubuntu1604
    pool:
      vmImage: ubuntu-16.04
    steps:
    # (PowerShell Core included in this Ubuntu image)

    # Install and run vcsim Docker container
    - script: |
        docker run --rm -d -p 443:443/tcp nimmis/vcsim
      displayName: 'Run vCenter Simulator container'
    
    # Run Pester tests
    - script: |
        pwsh -c '.\build.ps1'
      displayName: 'Build and Test'
    
    # Analyze test results
    - task: PublishTestResults@2
      inputs:
        testRunner:          'NUnit'
        testResultsFiles:    '**/TestResults.xml'
        testRunTitle:        'Ubuntu1604'
      displayName: 'Publish Test Results'

    # Fail the build if any tests failed
    # https://github.com/Microsoft/azure-pipelines-tasks/issues/1268#issuecomment-433056150
    - powershell: |
        $NUnitXML = '**/TestResults.xml'
        $(Get-Content $NUnitXML | Out-String) -match 'failures="(.*?)"'
        if ($matches[1] -eq 0)
        {
          Write-Host "No test failures"
        }
        else
        {
          # note that this will produce $LASTEXITCODE=1
          Write-Error "$($matches[1]) tests failed"
        }
      displayName: Check for Test Failures
